### ISSUE TITLE
Auth Feature -> SignUp Screen

### ISSUE THREAD

**Issue by werainkhatri** [ECellNitrr/teesco-app#10]
Is your feature request related to a problem? Please describe.

Folder structure: features -> auth. A single screen with name, email, institution, phone number(max length 10), country code(max length: 6) and password, signup buttons along with forgot password and login redirects
Describe the solution you'd like

1. all fields with appropriate validations (check the internet for validations)
2. api handling functions
3. dummy redirects

**Comment by divy-arpit** [comment]
I would like to handle this issue!
