### ISSUE TITLE
Auth Feature -> Forgot Password

### ISSUE THREAD

**Issue by werainkhatri** [ECellNitrr/teesco-app#11]
Is your feature request related to a problem? Please describe.

In auth feature. name functions and variables appropriately
3 subscreens:
1. enter mobile number (basic validation and basic UI)
2. an otp will be received on that number, screen for user to enter it in a textfield (6 digits asof now.)
3. if otp is correct, new and confirm password fields. appropriate validations required
4. if everything goes perfect -> log him in directly.

**Comment by TreavVasu** [comment]
I would take up this one.
