### ISSUE TITLE
Add bottom navbar

### ISSUE THREAD

**Issue by naveennvrgup** [ECellNitrr/teesco-app#20]
**Is your feature request related to a problem? Please describe.**
We need a navigation bar to go to different screens

**Describe the solution you'd like**

Add a bottom navbar with 5 routes (icons need not be final)
1. org_info
2. tasks
3. home
4. query section
5. leaderboard

Create folder structure for all the above screens. And add a simple placeholder widget for all the above routes.

**Comment by werainkhatri** [comment]
This is supposed to be a different screen than home screen right?

**Comment by Hard-Coder05** [comment]
@werainkhatri 
I am taking this issue. Please assign this to me!
