### ISSUE TITLE
clean pubspec.yaml

### ISSUE THREAD

**Issue by werainkhatri** [ECellNitrr/teesco-app#22]
**Describe the bug**
remove unwanted packages in pubspec
dependencies to remove :-
- chopper: ^3.0.2
- freezed_annotation: ^0.7.1
- flutter_bloc: ^3.2.0
- dartz: ^0.8.9

dev-dependencies to remove :- 
- chopper_generator: ^3.0.4
- freezed: ^0.10.6

**Expected behavior**
packages should be added as and when required by the code and not before hand

**Comment by naveennvrgup** [comment]
Let's keep bloc. Others can be removed. Needless to mention this is a not a priority now 😇

**Comment by Hard-Coder05** [comment]
@werainkhatri 
I am taking this issue. Please assign it to me. 
I have completed this one.
