### ISSUE TITLE
Org info screen UI

### ISSUE THREAD

**Issue by naveennvrgup** [ECellNitrr/teesco-app#37]
**Is your feature request related to a problem? Please describe.**
As a user, I should be able to see the details of the org I am a member of. 

![image](https://user-images.githubusercontent.com/33046846/83440556-c2319100-a462-11ea-801c-8cc40fa2c496.png)

**Describe the solution you'd like**
1. The social media icons are not needed in the beta release of our app. (as in the above img)

**Comment by Hard-Coder05** [comment]
I am taking this issue!
