### ISSUE TITLE
Group create screen UI

### ISSUE THREAD

**Issue by naveennvrgup** [ECellNitrr/teesco-app#38]
**Is your feature request related to a problem? Please describe.**
As an admin of the org I should be able to create groups.

![image](https://user-images.githubusercontent.com/33046846/83440973-6a475a00-a463-11ea-9667-40b595bbef01.png)

**Describe the solution you'd like**
1. Create the group create screen UI.
1. PermissionList widget should be dynamic. Should render permissions from a dictionary. Key=permission name, value=boolean.

**Comment by divy-arpit** [comment]
I would like to take up this issue. Kindly assign it to me.
