### ISSUE TITLE
Two Organisation List Screens

### ISSUE THREAD

**Issue by Hard-Coder05** [ECellNitrr/teesco-app#40]
**Describe the bug**
Due to PR #32 and #30 , Two Organisation List Screen have been created.

**Expected behavior**
There should be only one Organisation List Screen.

**How to Solve the bug**
Delete the screen created in PR #32 and make changes to the routes created in PR #32 . The screen created in PR #30 must be linked with the home button of the navBar!

**Screenshots**
![Screenshot_2020-06-02-10-53-45-731_com github android](https://user-images.githubusercontent.com/54059881/83495455-59373100-a4d5-11ea-93be-0345d35ecf73.jpg)

**Comment by aayushbisen** [comment]
On it 👍
