### ISSUE TITLE
leaderboard screen UI

### ISSUE THREAD

**Issue by naveennvrgup** [ECellNitrr/teesco-app#42]
**Is your feature request related to a problem? Please describe.**
As a volunteer to the org, I should be able to able to have a look at the leaderboard.

![image](https://user-images.githubusercontent.com/33046846/83520328-230ca800-a4fb-11ea-8a44-dec23d2be9b9.png)

**Describe the solution you'd like**
1. Create Leaderboard screen UI
1. the number on the left of the title indicates the user's points!
1. the first 3 people show have a gold, solver and bronze medal badge near their avatar. similar to 
![image](https://user-images.githubusercontent.com/33046846/83521104-5b60b600-a4fc-11ea-9638-8ae3776c48a3.png)

**Comment by Hard-Coder05** [comment]
I am taking this issue!
