### ISSUE TITLE
group list screen UI

### ISSUE THREAD

**Issue by naveennvrgup** [ECellNitrr/teesco-app#43]
**Is your feature request related to a problem? Please describe.**
As an admin of the org, I would like to view the list of groups under my Org.

![image](https://user-images.githubusercontent.com/33046846/83521441-dde97580-a4fc-11ea-9e9e-5bd8c907131b.png)

**Describe the solution you'd like**
1. create groups list screen UI.
1. The numbers on the side indicate `no of members in that group respectively`.

**Comment by aayushbisen** [comment]
Can I work on this?

**Comment by Hard-Coder05** [comment]
@aayushbisen In the above UI given, you don't have to create the bottom Navigation Bar as It is already created!

**Comment by aayushbisen** [comment]
Okay.

The `number of members` in group should be hard-coded for now or fetched from the API?

**Comment by Hard-Coder05** [comment]
hard coded for now
