### ISSUE TITLE
group members list screen UI

### ISSUE THREAD

**Issue by naveennvrgup** [ECellNitrr/teesco-app#44]
**Is your feature request related to a problem? Please describe.**
As an admin of the org I would like to view the members of the groups under the org. 

![image](https://user-images.githubusercontent.com/33046846/83521697-391b6800-a4fd-11ea-8c65-05c9c3aa86ec.png)

**Describe the solution you'd like**
1. create group members list screen UI
1. should be alphabetically ordered similar to a contacts app.
1. Divided into alphabetic sections

**Comment by divy-arpit** [comment]
I would like to take up this issue.
