### ISSUE TITLE
logged in user should be automatically routed to org list screen

### ISSUE THREAD

**Issue by naveennvrgup** [ECellNitrr/teesco-app#49]
**Is your feature request related to a problem? Please describe.**
Currently, user have to log in to see the home screen every time. 

**Describe the solution you'd like**
When a logged-in user opens the app the user should be automatically taken to orgs list screen. 

**Describe alternatives you've considered**
Ideally last opened org should be open but since we have not wired up the org list api yet #36 it is a good enough fix for now.

**Comment by Hard-Coder05** [comment]
Taking this one!
