### ISSUE TITLE
query section screen UI

### ISSUE THREAD

**Issue by naveennvrgup** [ECellNitrr/teesco-app#52]
![image](https://user-images.githubusercontent.com/33046846/83726672-80bb0480-a661-11ea-8dd5-42153c37eab7.png)

**Describe the solution you'd like**
build the query section screen with below widgets:
1. query_message widget which can be customized with the following inputs to the constructor
    1. messageId
    1. message
    1. timestamp
    1. authorName (if the messge is sent by the logged in user then no need to show the name. also message sent by the loggedin_user is on the right and others will be on the left)
1. query_input which should support multiline
1. submit_query which is the button which sends the query to the backend.

**Comment by sahil9001** [comment]
Working on this
